import DOMPurify from "dompurify";

/**
 * Sanitizes rich HTML generated by rich text editors (Quill, etc.)
 * to prevent XSS and malicious payloads while preserving legitimate formatting.
 */
export function sanitizeRichHtml(rawHtml: string): string {
  if (!rawHtml || typeof rawHtml !== "string") return "";

  if (typeof window === "undefined") {
    // Basic server-side guard
    return rawHtml.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "");
  }

  return DOMPurify.sanitize(rawHtml, {
    ALLOWED_TAGS: [
      "p", "br", "strong", "b", "em", "i", "u", "s", "strike",
      "h1", "h2", "h3", "h4", "h5", "h6",
      "blockquote", "code", "pre", "span",
      "ul", "ol", "li",
      "a", "hr"
    ],
    ALLOWED_ATTR: [
      "href", "target", "rel", "class", "style", "title"
    ],
    ALLOWED_URI_REGEXP: /^(?:(?:(?:f|ht)tps?|mailto|tel):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,
  });
}

/**
 * Strips HTML tags to produce a clean plain-text string,
 * suitable for LLM prompts, snippets, or word count calculation.
 */
export function stripHtml(html: string): string {
  if (!html || typeof html !== "string") return "";
  
  // Replace break and paragraph tags with newlines/spaces
  const formatted = html
    .replace(/<br\s*[\/]?>/gi, "\n")
    .replace(/<\/p>/gi, "\n")
    .replace(/<\/li>/gi, "\n")
    .replace(/<\/h[1-6]>/gi, "\n\n");
    
  return formatted
    .replace(/<[^>]*>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .trim();
}

/**
 * Checks if a content string contains rich HTML formatting elements.
 */
export function isRichHtml(content: string): boolean {
  if (!content || typeof content !== "string") return false;
  // Match common rich text tags produced by Quill
  return /<(p|h[1-6]|strong|em|u|s|blockquote|ul|ol|li|pre|code|span)[^>]*>/i.test(content);
}

/**
 * Formats a clean excerpt preview from rich HTML or plain text.
 */
export function createExcerpt(content: string, maxLen = 120): string {
  const plain = stripHtml(content);
  if (plain.length <= maxLen) return plain;
  return plain.slice(0, maxLen).trim() + "...";
}
